spring:
  datasource:
    url: ${TEST_DATABASE_URL}
    username: ${TEST_DATABASE_USERNAME}
    password: ${TEST_DATABASE_PASSWORD}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 55MB
      max-request-size: 60MB

  config:
    activate:
      on-profile: "dev"

  data:
    redis:
      host: redis
      port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: taquangvinh.study@gmail.com
    password: tuof bskn fgud szvk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
logging:
  level:
    org.springframework.type: TRACE
    org.hibernate.SQL: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.mapstruct: DEBUG
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}

stripe:
  api:
    key: ${STRIPE_SECRET_KEY}
  webhook:
    secret: ${STRIPE_WEBHOOK_SECRET}

embedding:
  service:
    url: http://localhost:5000

clockify:
  api:
    key: ${CLOCKIFY_API_KEY}
    base_url: https://api.clockify.me/api/v1
    header:
      key_name: X-Api-Key
  reports:
    base_url: https://reports.api.clockify.me/v1
  workspace:
    default_id: 69055ed8133ebe6373fc9c18

toggl:
  api_key: ${TOGGL_API_KEY}
  workspace:
    id: 20938694
  base_url: "https://api.track.toggl.com/api/v9"
  organization_id: 20939604


