spring:
  datasource:
    url: ${TEST_DATABASE_URL}
    username: ${TEST_DATABASE_USERNAME}
    password: ${TEST_DATABASE_PASSWORD}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 55MB
      max-request-size: 60MB

  config:
    activate:
      on-profile: "dev"

  data:
    redis:
      host: redis
      port: 6379
logging:
  level:
    org.springframework.type: TRACE
    org.hibernate.SQL: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.mapstruct: DEBUG
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}

stripe:
  api:
    key: ${STRIPE_SECRET_KEY}
  webhook:
    secret: ${STRIPE_WEBHOOK_SECRET}

embedding:
  service:
    url: http://localhost:5000

