spring:
  datasource:
    url: ${TEST_DATABASE_URL}
    username: ${TEST_DATABASE_USERNAME}
    password: ${TEST_DATABASE_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  config:
    activate:
      on-profile: "dev"
logging:
  level:
    org.springframework.type: TRACE
    org.hibernate.SQL:
    org.mapstruct: DEBUG
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
