spring:
  application:
    name: FreelancerBackend
  datasource:
    url: "jdbc:postgresql://localhost:5432/freelancer-test"
    username: postgres
    password: $232$TQV
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
#  config:
#    import: "application-dev.yml"
#  profiles:
#    active: "dev"
logging:
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}